CREATE DATABASE CATALAGO;
GO

USE CATALAGO;
GO

CREATE TABLE GENERO (
	idGenero TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeGenero VARCHAR(20) 
);
GO

CREATE TABLE FILME (
	idFilme TINYINT PRIMARY KEY IDENTITY(1,1),
	idGenero TINYINT FOREIGN KEY REFERENCES GENERO(idGenero),
	tituloFilme VARCHAR(80)
);
GO